### PR TITLE
Make all acc test pass

### PR DESCRIPTION
**Pull request by zengchen1024**

### CODE REVIEW

**Comment by h00130372** [comment]
About the networking port acctests, we don't have to specify the "security_group_ids" for port creation, this parameter is not required, and I read the api doc, if there is no securitygroups just left blank, so modify the code of port creation will fix the acctests problem. I will propose a commit to fix this.

**Comment by freesky-edward** [comment]
please ignore the failure of CI, it causes by CI itself. I already fix it on master.

**Comment by freesky-edward** [comment]
please ignore the failure of CI, it causes by CI itself. I already fix it on master.

**Comment by freesky-edward** [comment]
please ignore the failure of CI, it causes by CI itself. I already fix it on master.

**Comment by h00130372** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Comment by h00130372** [comment]
recheck

**Pull request merged**
